/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as LayoutNavigationTabsImport } from "./routes/_layout/navigation/tabs"
import { Route as LayoutNavigationStepsImport } from "./routes/_layout/navigation/steps"
import { Route as LayoutNavigationPaginationImport } from "./routes/_layout/navigation/pagination"
import { Route as LayoutNavigationMenuImport } from "./routes/_layout/navigation/menu"
import { Route as LayoutNavigationDropdownImport } from "./routes/_layout/navigation/dropdown"
import { Route as LayoutNavigationBreadcrumbImport } from "./routes/_layout/navigation/breadcrumb"
import { Route as LayoutNavigationAnchorImport } from "./routes/_layout/navigation/anchor"
import { Route as LayoutLayoutSpaceImport } from "./routes/_layout/layout/space"
import { Route as LayoutLayoutLayoutImport } from "./routes/_layout/layout/layout"
import { Route as LayoutLayoutGridImport } from "./routes/_layout/layout/grid"
import { Route as LayoutLayoutFlexImport } from "./routes/_layout/layout/flex"
import { Route as LayoutLayoutDividerImport } from "./routes/_layout/layout/divider"
import { Route as LayoutGeneralTypographyImport } from "./routes/_layout/general/typography"
import { Route as LayoutGeneralIconImport } from "./routes/_layout/general/icon"
import { Route as LayoutGeneralFloatButtonImport } from "./routes/_layout/general/float-button"
import { Route as LayoutGeneralButtonImport } from "./routes/_layout/general/button"
import { Route as LayoutDataEntrySliderImport } from "./routes/_layout/data-entry/slider"
import { Route as LayoutDataEntryInputImport } from "./routes/_layout/data-entry/input"
import { Route as LayoutDataDisplayTagImport } from "./routes/_layout/data-display/tag"

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNavigationTabsRoute = LayoutNavigationTabsImport.update({
  id: "/navigation/tabs",
  path: "/navigation/tabs",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNavigationStepsRoute = LayoutNavigationStepsImport.update({
  id: "/navigation/steps",
  path: "/navigation/steps",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNavigationPaginationRoute = LayoutNavigationPaginationImport.update(
  {
    id: "/navigation/pagination",
    path: "/navigation/pagination",
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutNavigationMenuRoute = LayoutNavigationMenuImport.update({
  id: "/navigation/menu",
  path: "/navigation/menu",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNavigationDropdownRoute = LayoutNavigationDropdownImport.update({
  id: "/navigation/dropdown",
  path: "/navigation/dropdown",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNavigationBreadcrumbRoute = LayoutNavigationBreadcrumbImport.update(
  {
    id: "/navigation/breadcrumb",
    path: "/navigation/breadcrumb",
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutNavigationAnchorRoute = LayoutNavigationAnchorImport.update({
  id: "/navigation/anchor",
  path: "/navigation/anchor",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutSpaceRoute = LayoutLayoutSpaceImport.update({
  id: "/layout/space",
  path: "/layout/space",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutLayoutRoute = LayoutLayoutLayoutImport.update({
  id: "/layout/layout",
  path: "/layout/layout",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutGridRoute = LayoutLayoutGridImport.update({
  id: "/layout/grid",
  path: "/layout/grid",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutFlexRoute = LayoutLayoutFlexImport.update({
  id: "/layout/flex",
  path: "/layout/flex",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutDividerRoute = LayoutLayoutDividerImport.update({
  id: "/layout/divider",
  path: "/layout/divider",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGeneralTypographyRoute = LayoutGeneralTypographyImport.update({
  id: "/general/typography",
  path: "/general/typography",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGeneralIconRoute = LayoutGeneralIconImport.update({
  id: "/general/icon",
  path: "/general/icon",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGeneralFloatButtonRoute = LayoutGeneralFloatButtonImport.update({
  id: "/general/float-button",
  path: "/general/float-button",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGeneralButtonRoute = LayoutGeneralButtonImport.update({
  id: "/general/button",
  path: "/general/button",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDataEntrySliderRoute = LayoutDataEntrySliderImport.update({
  id: "/data-entry/slider",
  path: "/data-entry/slider",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDataEntryInputRoute = LayoutDataEntryInputImport.update({
  id: "/data-entry/input",
  path: "/data-entry/input",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDataDisplayTagRoute = LayoutDataDisplayTagImport.update({
  id: "/data-display/tag",
  path: "/data-display/tag",
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/data-display/tag": {
      id: "/_layout/data-display/tag"
      path: "/data-display/tag"
      fullPath: "/data-display/tag"
      preLoaderRoute: typeof LayoutDataDisplayTagImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/data-entry/input": {
      id: "/_layout/data-entry/input"
      path: "/data-entry/input"
      fullPath: "/data-entry/input"
      preLoaderRoute: typeof LayoutDataEntryInputImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/data-entry/slider": {
      id: "/_layout/data-entry/slider"
      path: "/data-entry/slider"
      fullPath: "/data-entry/slider"
      preLoaderRoute: typeof LayoutDataEntrySliderImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/general/button": {
      id: "/_layout/general/button"
      path: "/general/button"
      fullPath: "/general/button"
      preLoaderRoute: typeof LayoutGeneralButtonImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/general/float-button": {
      id: "/_layout/general/float-button"
      path: "/general/float-button"
      fullPath: "/general/float-button"
      preLoaderRoute: typeof LayoutGeneralFloatButtonImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/general/icon": {
      id: "/_layout/general/icon"
      path: "/general/icon"
      fullPath: "/general/icon"
      preLoaderRoute: typeof LayoutGeneralIconImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/general/typography": {
      id: "/_layout/general/typography"
      path: "/general/typography"
      fullPath: "/general/typography"
      preLoaderRoute: typeof LayoutGeneralTypographyImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/layout/divider": {
      id: "/_layout/layout/divider"
      path: "/layout/divider"
      fullPath: "/layout/divider"
      preLoaderRoute: typeof LayoutLayoutDividerImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/layout/flex": {
      id: "/_layout/layout/flex"
      path: "/layout/flex"
      fullPath: "/layout/flex"
      preLoaderRoute: typeof LayoutLayoutFlexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/layout/grid": {
      id: "/_layout/layout/grid"
      path: "/layout/grid"
      fullPath: "/layout/grid"
      preLoaderRoute: typeof LayoutLayoutGridImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/layout/layout": {
      id: "/_layout/layout/layout"
      path: "/layout/layout"
      fullPath: "/layout/layout"
      preLoaderRoute: typeof LayoutLayoutLayoutImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/layout/space": {
      id: "/_layout/layout/space"
      path: "/layout/space"
      fullPath: "/layout/space"
      preLoaderRoute: typeof LayoutLayoutSpaceImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/anchor": {
      id: "/_layout/navigation/anchor"
      path: "/navigation/anchor"
      fullPath: "/navigation/anchor"
      preLoaderRoute: typeof LayoutNavigationAnchorImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/breadcrumb": {
      id: "/_layout/navigation/breadcrumb"
      path: "/navigation/breadcrumb"
      fullPath: "/navigation/breadcrumb"
      preLoaderRoute: typeof LayoutNavigationBreadcrumbImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/dropdown": {
      id: "/_layout/navigation/dropdown"
      path: "/navigation/dropdown"
      fullPath: "/navigation/dropdown"
      preLoaderRoute: typeof LayoutNavigationDropdownImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/menu": {
      id: "/_layout/navigation/menu"
      path: "/navigation/menu"
      fullPath: "/navigation/menu"
      preLoaderRoute: typeof LayoutNavigationMenuImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/pagination": {
      id: "/_layout/navigation/pagination"
      path: "/navigation/pagination"
      fullPath: "/navigation/pagination"
      preLoaderRoute: typeof LayoutNavigationPaginationImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/steps": {
      id: "/_layout/navigation/steps"
      path: "/navigation/steps"
      fullPath: "/navigation/steps"
      preLoaderRoute: typeof LayoutNavigationStepsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/navigation/tabs": {
      id: "/_layout/navigation/tabs"
      path: "/navigation/tabs"
      fullPath: "/navigation/tabs"
      preLoaderRoute: typeof LayoutNavigationTabsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDataDisplayTagRoute: typeof LayoutDataDisplayTagRoute
  LayoutDataEntryInputRoute: typeof LayoutDataEntryInputRoute
  LayoutDataEntrySliderRoute: typeof LayoutDataEntrySliderRoute
  LayoutGeneralButtonRoute: typeof LayoutGeneralButtonRoute
  LayoutGeneralFloatButtonRoute: typeof LayoutGeneralFloatButtonRoute
  LayoutGeneralIconRoute: typeof LayoutGeneralIconRoute
  LayoutGeneralTypographyRoute: typeof LayoutGeneralTypographyRoute
  LayoutLayoutDividerRoute: typeof LayoutLayoutDividerRoute
  LayoutLayoutFlexRoute: typeof LayoutLayoutFlexRoute
  LayoutLayoutGridRoute: typeof LayoutLayoutGridRoute
  LayoutLayoutLayoutRoute: typeof LayoutLayoutLayoutRoute
  LayoutLayoutSpaceRoute: typeof LayoutLayoutSpaceRoute
  LayoutNavigationAnchorRoute: typeof LayoutNavigationAnchorRoute
  LayoutNavigationBreadcrumbRoute: typeof LayoutNavigationBreadcrumbRoute
  LayoutNavigationDropdownRoute: typeof LayoutNavigationDropdownRoute
  LayoutNavigationMenuRoute: typeof LayoutNavigationMenuRoute
  LayoutNavigationPaginationRoute: typeof LayoutNavigationPaginationRoute
  LayoutNavigationStepsRoute: typeof LayoutNavigationStepsRoute
  LayoutNavigationTabsRoute: typeof LayoutNavigationTabsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDataDisplayTagRoute: LayoutDataDisplayTagRoute,
  LayoutDataEntryInputRoute: LayoutDataEntryInputRoute,
  LayoutDataEntrySliderRoute: LayoutDataEntrySliderRoute,
  LayoutGeneralButtonRoute: LayoutGeneralButtonRoute,
  LayoutGeneralFloatButtonRoute: LayoutGeneralFloatButtonRoute,
  LayoutGeneralIconRoute: LayoutGeneralIconRoute,
  LayoutGeneralTypographyRoute: LayoutGeneralTypographyRoute,
  LayoutLayoutDividerRoute: LayoutLayoutDividerRoute,
  LayoutLayoutFlexRoute: LayoutLayoutFlexRoute,
  LayoutLayoutGridRoute: LayoutLayoutGridRoute,
  LayoutLayoutLayoutRoute: LayoutLayoutLayoutRoute,
  LayoutLayoutSpaceRoute: LayoutLayoutSpaceRoute,
  LayoutNavigationAnchorRoute: LayoutNavigationAnchorRoute,
  LayoutNavigationBreadcrumbRoute: LayoutNavigationBreadcrumbRoute,
  LayoutNavigationDropdownRoute: LayoutNavigationDropdownRoute,
  LayoutNavigationMenuRoute: LayoutNavigationMenuRoute,
  LayoutNavigationPaginationRoute: LayoutNavigationPaginationRoute,
  LayoutNavigationStepsRoute: LayoutNavigationStepsRoute,
  LayoutNavigationTabsRoute: LayoutNavigationTabsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/data-display/tag": typeof LayoutDataDisplayTagRoute
  "/data-entry/input": typeof LayoutDataEntryInputRoute
  "/data-entry/slider": typeof LayoutDataEntrySliderRoute
  "/general/button": typeof LayoutGeneralButtonRoute
  "/general/float-button": typeof LayoutGeneralFloatButtonRoute
  "/general/icon": typeof LayoutGeneralIconRoute
  "/general/typography": typeof LayoutGeneralTypographyRoute
  "/layout/divider": typeof LayoutLayoutDividerRoute
  "/layout/flex": typeof LayoutLayoutFlexRoute
  "/layout/grid": typeof LayoutLayoutGridRoute
  "/layout/layout": typeof LayoutLayoutLayoutRoute
  "/layout/space": typeof LayoutLayoutSpaceRoute
  "/navigation/anchor": typeof LayoutNavigationAnchorRoute
  "/navigation/breadcrumb": typeof LayoutNavigationBreadcrumbRoute
  "/navigation/dropdown": typeof LayoutNavigationDropdownRoute
  "/navigation/menu": typeof LayoutNavigationMenuRoute
  "/navigation/pagination": typeof LayoutNavigationPaginationRoute
  "/navigation/steps": typeof LayoutNavigationStepsRoute
  "/navigation/tabs": typeof LayoutNavigationTabsRoute
}

export interface FileRoutesByTo {
  "/": typeof LayoutIndexRoute
  "/data-display/tag": typeof LayoutDataDisplayTagRoute
  "/data-entry/input": typeof LayoutDataEntryInputRoute
  "/data-entry/slider": typeof LayoutDataEntrySliderRoute
  "/general/button": typeof LayoutGeneralButtonRoute
  "/general/float-button": typeof LayoutGeneralFloatButtonRoute
  "/general/icon": typeof LayoutGeneralIconRoute
  "/general/typography": typeof LayoutGeneralTypographyRoute
  "/layout/divider": typeof LayoutLayoutDividerRoute
  "/layout/flex": typeof LayoutLayoutFlexRoute
  "/layout/grid": typeof LayoutLayoutGridRoute
  "/layout/layout": typeof LayoutLayoutLayoutRoute
  "/layout/space": typeof LayoutLayoutSpaceRoute
  "/navigation/anchor": typeof LayoutNavigationAnchorRoute
  "/navigation/breadcrumb": typeof LayoutNavigationBreadcrumbRoute
  "/navigation/dropdown": typeof LayoutNavigationDropdownRoute
  "/navigation/menu": typeof LayoutNavigationMenuRoute
  "/navigation/pagination": typeof LayoutNavigationPaginationRoute
  "/navigation/steps": typeof LayoutNavigationStepsRoute
  "/navigation/tabs": typeof LayoutNavigationTabsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/data-display/tag": typeof LayoutDataDisplayTagRoute
  "/_layout/data-entry/input": typeof LayoutDataEntryInputRoute
  "/_layout/data-entry/slider": typeof LayoutDataEntrySliderRoute
  "/_layout/general/button": typeof LayoutGeneralButtonRoute
  "/_layout/general/float-button": typeof LayoutGeneralFloatButtonRoute
  "/_layout/general/icon": typeof LayoutGeneralIconRoute
  "/_layout/general/typography": typeof LayoutGeneralTypographyRoute
  "/_layout/layout/divider": typeof LayoutLayoutDividerRoute
  "/_layout/layout/flex": typeof LayoutLayoutFlexRoute
  "/_layout/layout/grid": typeof LayoutLayoutGridRoute
  "/_layout/layout/layout": typeof LayoutLayoutLayoutRoute
  "/_layout/layout/space": typeof LayoutLayoutSpaceRoute
  "/_layout/navigation/anchor": typeof LayoutNavigationAnchorRoute
  "/_layout/navigation/breadcrumb": typeof LayoutNavigationBreadcrumbRoute
  "/_layout/navigation/dropdown": typeof LayoutNavigationDropdownRoute
  "/_layout/navigation/menu": typeof LayoutNavigationMenuRoute
  "/_layout/navigation/pagination": typeof LayoutNavigationPaginationRoute
  "/_layout/navigation/steps": typeof LayoutNavigationStepsRoute
  "/_layout/navigation/tabs": typeof LayoutNavigationTabsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/"
    | "/data-display/tag"
    | "/data-entry/input"
    | "/data-entry/slider"
    | "/general/button"
    | "/general/float-button"
    | "/general/icon"
    | "/general/typography"
    | "/layout/divider"
    | "/layout/flex"
    | "/layout/grid"
    | "/layout/layout"
    | "/layout/space"
    | "/navigation/anchor"
    | "/navigation/breadcrumb"
    | "/navigation/dropdown"
    | "/navigation/menu"
    | "/navigation/pagination"
    | "/navigation/steps"
    | "/navigation/tabs"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/data-display/tag"
    | "/data-entry/input"
    | "/data-entry/slider"
    | "/general/button"
    | "/general/float-button"
    | "/general/icon"
    | "/general/typography"
    | "/layout/divider"
    | "/layout/flex"
    | "/layout/grid"
    | "/layout/layout"
    | "/layout/space"
    | "/navigation/anchor"
    | "/navigation/breadcrumb"
    | "/navigation/dropdown"
    | "/navigation/menu"
    | "/navigation/pagination"
    | "/navigation/steps"
    | "/navigation/tabs"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/"
    | "/_layout/data-display/tag"
    | "/_layout/data-entry/input"
    | "/_layout/data-entry/slider"
    | "/_layout/general/button"
    | "/_layout/general/float-button"
    | "/_layout/general/icon"
    | "/_layout/general/typography"
    | "/_layout/layout/divider"
    | "/_layout/layout/flex"
    | "/_layout/layout/grid"
    | "/_layout/layout/layout"
    | "/_layout/layout/space"
    | "/_layout/navigation/anchor"
    | "/_layout/navigation/breadcrumb"
    | "/_layout/navigation/dropdown"
    | "/_layout/navigation/menu"
    | "/_layout/navigation/pagination"
    | "/_layout/navigation/steps"
    | "/_layout/navigation/tabs"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/data-display/tag",
        "/_layout/data-entry/input",
        "/_layout/data-entry/slider",
        "/_layout/general/button",
        "/_layout/general/float-button",
        "/_layout/general/icon",
        "/_layout/general/typography",
        "/_layout/layout/divider",
        "/_layout/layout/flex",
        "/_layout/layout/grid",
        "/_layout/layout/layout",
        "/_layout/layout/space",
        "/_layout/navigation/anchor",
        "/_layout/navigation/breadcrumb",
        "/_layout/navigation/dropdown",
        "/_layout/navigation/menu",
        "/_layout/navigation/pagination",
        "/_layout/navigation/steps",
        "/_layout/navigation/tabs"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/data-display/tag": {
      "filePath": "_layout/data-display/tag.tsx",
      "parent": "/_layout"
    },
    "/_layout/data-entry/input": {
      "filePath": "_layout/data-entry/input.tsx",
      "parent": "/_layout"
    },
    "/_layout/data-entry/slider": {
      "filePath": "_layout/data-entry/slider.tsx",
      "parent": "/_layout"
    },
    "/_layout/general/button": {
      "filePath": "_layout/general/button.tsx",
      "parent": "/_layout"
    },
    "/_layout/general/float-button": {
      "filePath": "_layout/general/float-button.tsx",
      "parent": "/_layout"
    },
    "/_layout/general/icon": {
      "filePath": "_layout/general/icon.tsx",
      "parent": "/_layout"
    },
    "/_layout/general/typography": {
      "filePath": "_layout/general/typography.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout/divider": {
      "filePath": "_layout/layout/divider.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout/flex": {
      "filePath": "_layout/layout/flex.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout/grid": {
      "filePath": "_layout/layout/grid.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout/layout": {
      "filePath": "_layout/layout/layout.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout/space": {
      "filePath": "_layout/layout/space.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/anchor": {
      "filePath": "_layout/navigation/anchor.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/breadcrumb": {
      "filePath": "_layout/navigation/breadcrumb.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/dropdown": {
      "filePath": "_layout/navigation/dropdown.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/menu": {
      "filePath": "_layout/navigation/menu.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/pagination": {
      "filePath": "_layout/navigation/pagination.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/steps": {
      "filePath": "_layout/navigation/steps.tsx",
      "parent": "/_layout"
    },
    "/_layout/navigation/tabs": {
      "filePath": "_layout/navigation/tabs.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
